export enum profileEnum {
  ROLE_ADMINISTRADOR = 'ROLE_ADMINISTRADOR',
  ROLE_SUPORTE = 'ROLE_SUPORTE',
  ROLE_AUXILIAR_ADMINISTRATIVO = 'ROLE_AUXILIAR_ADMINISTRATIVO',
  ROLE_EMPRESA = 'ROLE_EMPRESA'
}


export enum TeamEnum {
  SUPORTE = "SUPORTE",
  TECNICO = "TECNICO"
}

export enum TicketEnum {
  ABERTO = "ABERTO",
  ALTERADO = "ALTERADO",

  EM_ANDAMENTO = "EM_ANDAMENTO",

  CANCELADO = "CANCELADO",

  CONCLUIDO = "CONCLUIDO"
}

