export enum ProfileEnum {
  ROLE_ADMINISTRADOR = 'ROLE_ADMINISTRADOR',
  ROLE_SUPORTE = 'ROLE_SUPORTE',
  ROLE_AUXILIAR_ADMINISTRATIVO = 'ROLE_AUXILIAR_ADMINISTRATIVO',
  ROLE_EMPRESA = 'ROLE_EMPRESA'
}
